version: '3.4'

services:

  sqlserver:
    container_name: churchee.sqldata
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "SqlServer2022!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  churchee.presentation.admin:
    image: ${DOCKER_REGISTRY-}churcheepresentationadmin
    build:
      context: .
      dockerfile: src/Churchee.Presentation.Admin/Dockerfile
